# Generated by Django 5.1.4 on 2025-01-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AddField(
            model_name='movie',
            name='movie',
            field=models.FileField(blank=True, null=True, upload_to='media/movie', verbose_name='Фильм'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.ImageField(upload_to='media/movie_art', verbose_name='Обложка'),
        ),
    ]
