# Generated by Django 5.1.4 on 2025-01-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='name',
            field=models.CharField(max_length=34, verbose_name='Наименование актера'),
        ),
    ]
